### ISSUE TITLE
Tab Label Setting

### ISSUE THREAD

**Issue by broiyn** [kat066/biglunchbox-pomodoro#16]
**Requirements**
- When the timer is running, the tab will display remaining time and which phase it is on (focus, break, or long break).
- The setting can be turned on/off with a toggle in settings.
- The setting will be turned on by default
- The user's preference (on/off) will be saved in localStorage

**Tasks**
- [x] Design Use Cases
- [x] Implement MVP
- [x] Document behavior tests
- [x] Create unit + integration tests
